export const EventData = [
  {
    id: 1,
    date: 'YYYY_MM_DD',
    company: '맨들맨들1',
    owner: '정우성',
    area: '경기',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '등록',
    detail: '상세',
  },
  {
    id: 2,
    date: 'YYYY_MM_DD',
    company: '맨들맨들2',
    owner: '강경준',
    area: '경기',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '심사',
    detail: '상세',
  },
  {
    id: 3,
    date: 'YYYY_MM_DD',
    company: '맨들맨들3',
    owner: '송강',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '승인불가',
    detail: '상세',
  },
  {
    id: 4,
    date: 'YYYY_MM_DD',
    company: '맨들맨들5',
    owner: '서지석',
    area: '서울',
    grade: '파트너',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 5,
    date: 'YYYY_MM_DD',
    company: '맨들맨들5',
    owner: '권혁수',
    area: '서울',
    grade: '파트너',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 6,
    date: 'YYYY_MM_DD',
    company: '맨들맨들6',
    owner: '권혁수',
    area: '공유',
    grade: '서울',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 7,
    date: 'YYYY_MM_DD',
    company: '맨들맨들7',
    owner: '박서준',
    area: '서울',
    grade: 'FC',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 8,
    date: 'YYYY_MM_DD',
    company: '맨들맨들8',
    owner: '박광현',
    area: '서울',
    grade: 'FC',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 9,
    date: 'YYYY_MM_DD',
    company: '맨들맨들9',
    owner: '송중기',
    area: '서울',
    grade: '파트너',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 10,
    date: 'YYYY_MM_DD',
    company: '맨들맨들10',
    owner: '신성록',
    area: '서울',
    grade: '파트너',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 11,
    date: 'YYYY_MM_DD',
    company: '맨들맨들11',
    owner: '정지훈',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 12,
    date: 'YYYY_MM_DD',
    company: '맨들맨들12',
    owner: '정일우',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 13,
    date: 'YYYY_MM_DD',
    company: '맨들맨들13',
    owner: '이서진',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 14,
    date: 'YYYY_MM_DD',
    company: '맨들맨들14',
    owner: '이성열',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 15,
    date: 'YYYY_MM_DD',
    company: '맨들맨들15',
    owner: '강태오',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 16,
    date: 'YYYY_MM_DD',
    company: '맨들맨들16',
    owner: '옥택연',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 17,
    date: 'YYYY_MM_DD',
    company: '맨들맨들17',
    owner: '유재석',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 18,
    date: 'YYYY_MM_DD',
    company: '맨들맨들18',
    owner: '강동원',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 19,
    date: 'YYYY_MM_DD',
    company: '맨들맨들19',
    owner: '원슈타인',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 20,
    date: 'YYYY_MM_DD',
    company: '맨들맨들20',
    owner: '박해진',
    area: '서울',
    grade: '일반',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 21,
    date: 'YYYY_MM_DD',
    company: '맨들맨들21',
    owner: '류진',
    area: '서울',
    grade: '파트너',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 22,
    date: 'YYYY_MM_DD',
    company: '맨들맨들22',
    owner: '조승우',
    area: '서울',
    grade: 'FC',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 23,
    date: 'YYYY_MM_DD',
    company: '맨들맨들',
    owner: '홍길동',
    area: '서울',
    grade: 'FC',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 24,
    date: 'YYYY_MM_DD',
    company: '맨들맨들',
    owner: '홍길동',
    area: '서울',
    grade: '파트너',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    price: 100000,
    sales: 80000,
    terms: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
];

export const RegisterData = [
  {
    id: 1,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '등록',
    detail: '상세',
  },
  {
    id: 2,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '등록',
    detail: '상세',
  },
  {
    id: 3,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '승인불가',
    detail: '상세',
  },
  {
    id: 4,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '승인불가',
    detail: '상세',
  },
  {
    id: 5,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '승인불가',
    detail: '상세',
  },
  {
    id: 6,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '승인불가',
    detail: '상세',
  },
  {
    id: 7,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '승인불가',
    detail: '상세',
  },
  {
    id: 8,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '승인불가',
    detail: '상세',
  },
  {
    id: 9,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 10,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 11,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 12,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 13,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 14,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 15,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 16,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 17,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
  {
    id: 18,
    date: 'YYYY_MM_DD',
    category: '네일아트',
    event: '12월 연말 할인 이벤트',
    pay: 100000,
    sales: 80000,
    term: 'YYYY-MM-DD  ~ YYYY-MM-DD',
    status: '진행',
    detail: '상세',
  },
];
