export const MembersShopData = [
  {
    id: 1,
    company: '맨들맨들1',
    owner: '정우성',
    area: '경기',
    grade: '일반',
    manager: '박동휘',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 2,
    company: '맨들맨들2',
    owner: '강경준',
    area: '경기',
    grade: '일반',
    manager: '박동휘',
    phone: '010-1111-2222',
    service: '대기',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Premiun',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 3,
    company: '맨들맨들3',
    owner: '송강',
    area: '서울',
    grade: '일반',
    manager: '박동휘',
    phone: '010-1111-2222',
    service: '심사',
    ad: '-',
    sms: '-',
    coupon: '-',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 4,
    company: '맨들맨들5',
    owner: '서지석',
    area: '서울',
    grade: '파트너',
    manager: '박동휘',
    phone: '010-1111-2222',
    service: '대기',
    ad: '-',
    sms: '-',
    coupon: '-',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 5,
    company: '맨들맨들5',
    owner: '권혁수',
    area: '서울',
    grade: '파트너',
    manager: '박동휘',
    phone: '010-1111-2222',
    service: '승인',
    ad: '-',
    sms: '-',
    coupon: '-',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 6,
    company: '맨들맨들6',
    owner: '공유',
    area: '서울',
    grade: 'FC',
    manager: '박동휘',
    phone: '010-1111-2222',
    service: '승인',
    ad: '-',
    sms: '-',
    coupon: '-',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 7,
    company: '맨들맨들7',
    owner: '박서준',
    area: '서울',
    grade: 'FC',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '종료',
    sms: '종료',
    coupon: '종료',
    beautyManager: 'Premiun',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 8,
    company: '맨들맨들8',
    owner: '박광현',
    area: '서울',
    grade: 'FC',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 9,
    company: '맨들맨들9',
    owner: '송**',
    area: '서울',
    grade: '파트너',
    manager: '100',
    phone: '010-1111-2222',
    service: '취소',
    ad: '-',
    sms: '-',
    coupon: '-',
    beautyManager: '-',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 10,
    company: '맨들맨들10',
    owner: '신성록',
    area: '서울',
    grade: '파트너',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 11,
    company: '맨들맨들11',
    owner: '정지훈',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 12,
    company: '맨들맨들12',
    owner: '정일우',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 13,
    company: '맨들맨들13',
    owner: '이서진',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 14,
    company: '맨들맨들14',
    owner: '이성열',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 15,
    company: '맨들맨들15',
    owner: '강태오',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 16,
    company: '맨들맨들16',
    owner: '옥택연',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 17,
    company: '맨들맨들17',
    owner: '유재석',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 18,
    company: '맨들맨들18',
    owner: '강동원',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 19,
    company: '맨들맨들19',
    owner: '원슈타인',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 20,
    company: '맨들맨들20',
    owner: '박해진',
    area: '서울',
    grade: '일반',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 21,
    company: '맨들맨들21',
    owner: '류진',
    area: '서울',
    grade: '파트너',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 22,
    company: '맨들맨들22',
    owner: '조승우',
    area: '서울',
    grade: 'FC',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 23,
    company: '맨들맨들',
    owner: '홍길동',
    area: '서울',
    grade: 'FC',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 24,
    company: '맨들맨들',
    owner: '홍길동',
    area: '서울',
    grade: '파트너',
    manager: '100',
    phone: '010-1111-2222',
    service: '승인',
    ad: '이용중',
    sms: '이용중',
    coupon: '이용중',
    beautyManager: 'Basic',
    date: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
];

export const MembersGeneralData = [
  {
    id: 1,
    name: '정우성',
    nickname: '정우성',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 2,
    name: ' 강경준',
    nickname: ' 강경준',
    channel: '네이버',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 3,
    name: '송강',
    nickname: '송강',
    channel: '페이스북',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 4,
    name: '서지석',
    nickname: '서지석',
    channel: '애플',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 5,
    name: '권혁수',
    nickname: '권혁수',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 6,
    name: '공유',
    nickname: '공유',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 7,
    name: '박서준',
    nickname: '박서준',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 8,
    name: '박광현',
    nickname: '박광현',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 9,
    name: '송**',
    nickname: '-',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 10,
    name: '신성록',
    nickname: '신성록',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 11,
    name: '정지훈',
    nickname: '정지훈',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 12,
    name: '정일우',
    nickname: '정일우',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 13,
    name: '이서진',
    nickname: '이서진',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 14,
    name: '이성열',
    nickname: '이성열',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 15,
    name: '강태오',
    nickname: '강태오',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 16,
    name: '옥택연',
    nickname: '옥택연',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 17,
    name: '유재석',
    nickname: '유재석',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 18,
    name: '강동원',
    nickname: '강동원',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 19,
    name: '원슈타인',
    nickname: '원슈타인',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 20,
    name: '박해진',
    nickname: '박해진',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 21,
    name: '류진',
    nickname: '류진',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 22,
    name: '조승우',
    nickname: '조승우',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 23,
    name: '홍길동',
    nickname: '홍길동',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 24,
    name: '홍길동',
    nickname: '홍길동',
    channel: '카카오',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
];

export const MembersManagerData = [
  {
    id: 1,
    name: '김나래',
    signUpChannel: '대기',
    phone: '010-1111-2222',
    business: '플랫폼사업부',
    team: '-',
    authority: 'SuperAdmin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 2,
    name: '김수정',
    signUpChannel: '심사',
    phone: '010-1111-2222',
    business: '플랫폼사업부',
    team: '마케팅팀',
    authority: 'Admin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 3,
    name: '임은영',
    signUpChannel: '심사',
    phone: '010-1111-2222',
    business: '플랫폼사업부',
    team: '마케팅팀',
    authority: 'Admin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 4,
    name: '박동휘',
    signUpChannel: '심사',
    phone: '010-1111-2222',
    business: '플랫폼사업부',
    team: '영업팀',
    authority: 'Admin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 5,
    name: '지세형',
    signUpChannel: '승인',
    phone: '010-1111-2222',
    business: '플랫폼사업부',
    team: '영업팀',
    authority: 'Admin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 6,
    name: '염보영',
    signUpChannel: '승인',
    phone: '010-1111-2222',
    business: '플랫폼사업부',
    team: '디자인팀',
    authority: 'Admin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 7,
    name: '박실',
    signUpChannel: '승인',
    phone: '010-1111-2222',
    business: '플랫폼사업부',
    team: '개발팀',
    authority: 'SuperAdmin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 8,
    name: '김택곤',
    signUpChannel: '승인',
    phone: '010-1111-2222',
    business: '임원',
    team: '-',
    authority: 'Admin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 9,
    name: '방민규',
    signUpChannel: '취소',
    phone: '010-1111-2222',
    business: '대표',
    team: '-',
    authority: 'Admin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 10,
    name: '임현식',
    signUpChannel: '승인',
    phone: '010-1111-2222',
    business: '반도체사업부',
    team: '-',
    authority: 'Admin',
    recentLogin: 'YYYY-MM-DD',
  },
  {
    id: 11,
    name: '조남준',
    signUpChannel: '승인',
    phone: '010-1111-2222',
    business: '반도체사업부',
    team: '기술영업팀',
    authority: 'Admin',
    recentLogin: 'YYYY-MM-DD',
  },
];

export const ShopMemberData = [
  {
    id: 1,
    name: '정우성',
    nickname: '정우성',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 2,
    name: ' 강경준',
    nickname: ' 강경준',
    channel: '네이버',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 3,
    name: '송강',
    nickname: '송강',
    channel: '페이스북',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 4,
    name: '서지석',
    nickname: '서지석',
    channel: '애플',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 5,
    name: '권혁수',
    nickname: '권혁수',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 6,
    name: '공유',
    nickname: '공유',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 7,
    name: '박서준',
    nickname: '박서준',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 8,
    name: '박광현',
    nickname: '박광현',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 9,
    name: '송**',
    nickname: '-',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 10,
    name: '신성록',
    nickname: '신성록',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 11,
    name: '정지훈',
    nickname: '정지훈',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 12,
    name: '정일우',
    nickname: '정일우',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 13,
    name: '이서진',
    nickname: '이서진',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 14,
    name: '이성열',
    nickname: '이성열',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 15,
    name: '강태오',
    nickname: '강태오',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 16,
    name: '옥택연',
    nickname: '옥택연',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 17,
    name: '유재석',
    nickname: '유재석',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 18,
    name: '강동원',
    nickname: '강동원',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 19,
    name: '원슈타인',
    nickname: '원슈타인',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 20,
    name: '박해진',
    nickname: '박해진',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 21,
    name: '류진',
    nickname: '류진',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 22,
    name: '조승우',
    nickname: '조승우',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 23,
    name: '홍길동',
    nickname: '홍길동',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 24,
    name: '홍길동',
    nickname: '홍길동',
    channel: '카카오',
    grade: '일반',
    phone: '010-1111-2222',
    dateOfBirth: '99-01-01',
    age: '23',
    sex: '남자',
    reservationCase: 3,
    payment: 278000,
    point: 0,
    signUpDate: 'YYYY-MM-DD',
    recentLogin: 'YYYY-MM-DD',
    admin: '관리',
  },
];
