export const ProductsConData = [
  {
    id: 1,
    owner: '정우성',
    company: '맨들맨들1',
    area: '경기',
    grade: '일반',
    pdNum: 128,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 2,
    owner: '강경준',
    company: '맨들맨들2',
    area: '경기',
    grade: '일반',
    pdNum: 127,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 2,
    detail: '상세',
  },
  {
    id: 3,
    company: '맨들맨들3',
    owner: '송강',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 4,
    company: '맨들맨들5',
    owner: '서지석',
    area: '서울',
    grade: '파트너',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 5,
    company: '맨들맨들5',
    owner: '권혁수',
    area: '서울',
    grade: '파트너',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 6,
    company: '맨들맨들6',
    owner: '공유',
    area: '서울',
    grade: 'FC',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 7,
    company: '맨들맨들7',
    owner: '박서준',
    area: '서울',
    grade: 'FC',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 8,
    company: '맨들맨들8',
    owner: '박광현',
    area: '서울',
    grade: 'FC',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 9,
    company: '맨들맨들9',
    owner: '송중기',
    area: '서울',
    grade: '파트너',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 10,
    company: '맨들맨들10',
    owner: '신성록',
    area: '서울',
    grade: '파트너',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 11,
    company: '맨들맨들11',
    owner: '정지훈',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 12,
    company: '맨들맨들12',
    owner: '정일우',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 13,
    company: '맨들맨들13',
    owner: '이서진',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 14,
    company: '맨들맨들14',
    owner: '이성열',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 15,
    company: '맨들맨들15',
    owner: '강태오',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 16,
    company: '맨들맨들16',
    owner: '옥택연',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 17,
    company: '맨들맨들17',
    owner: '유재석',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 18,
    company: '맨들맨들18',
    owner: '강동원',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 19,
    company: '맨들맨들19',
    owner: '원슈타인',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 20,
    company: '맨들맨들20',
    owner: '박해진',
    area: '서울',
    grade: '일반',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 21,
    company: '맨들맨들21',
    owner: '류진',
    area: '서울',
    grade: '파트너',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 22,
    company: '맨들맨들22',
    owner: '조승우',
    area: '서울',
    grade: 'FC',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 23,
    company: '맨들맨들',
    owner: '홍길동',
    area: '서울',
    grade: 'FC',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 24,
    company: '맨들맨들',
    owner: '홍길동',
    area: '서울',
    grade: '파트너',
    pdNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
];

export const ProductsDetailData = [
  {
    id: 1,
    type: '일반',
    sex: '여자',
    classification: '손',
    pdName: '기본케어',
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 2,
    type: '일반',
    sex: '여자',
    classification: '손',
    pdName: '젤 프렌치',
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 3,
    type: '일반',
    sex: '여자',
    classification: '손',
    pdName: '젤 그라데이션',
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 4,
    type: '일반',
    sex: '남자',
    classification: '손',
    pdName: '기본케어',
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 5,
    type: '일반',
    sex: '남자',
    classification: '손',
    pdName: '기본케어',
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 6,
    type: '일반',
    sex: '남자',
    classification: '손',
    pdName: '기본케어',
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 7,
    type: '일반',
    sex: '공통',
    classification: '손',
    pdName: '파츠',
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 8,
    type: '일반',
    sex: '공통',
    classification: '손',
    pdName: '대학생 할인_기본케어 20,000',
    price: 20000,
    time: '30분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 9,
    type: '일반',
    sex: '공통',
    classification: '발',
    pdName: '대학생 할인_기본케어 30,000',
    price: 30000,
    time: '30분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 10,
    type: '일반',
    sex: '공통',
    classification: '손',
    pdName: '파츠',
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 11,
    type: '일반',
    sex: '공통',
    classification: '손',
    pdName: '파츠',
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매종료' }],
  },
];

export const ProductsDetailMoneyTicketData = [
  {
    id: 1,
    type: '일반',
    sex: '여자',
    pdName: '네일 금액권  20만원',
    price: 100000,
    bonus: 20000,
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 2,
    type: '일반',
    sex: '여자',
    pdName: '피부 금액권 20만원',
    price: 100000,
    bonus: 20000,
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 3,
    type: '일반',
    sex: '공통',
    pdName: '왁싱 금액권 20만원',
    price: 100000,
    bonus: 20000,
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 4,
    type: '일반',
    sex: '공통',
    pdName: '속눈썹 금액권 20만원',
    price: 100000,
    bonus: 20000,
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 5,
    type: '일반',
    sex: '공통',
    pdName: '20만원권',
    price: 100000,
    bonus: 20000,
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 6,
    type: '일반',
    sex: '공통',
    pdName: '30만원권',
    price: 100000,
    bonus: 30000,
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 7,
    type: '일반',
    sex: '공통',
    pdName: '50만원권',
    price: 100000,
    bonus: 50000,
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 8,
    type: '이벤트',
    sex: '공통',
    pdName: '100 만원권',
    price: 20000,
    bonus: 100000,
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 9,
    type: '이벤트',
    sex: '공통',
    pdName: '200 만원권',
    price: 30000,
    bonus: 300000,
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
];

export const ProductsDetailSeasonTicketData = [
  {
    id: 1,
    type: '일반',
    sex: '여자',
    category: '손',
    pdName: '기본케어',
    num: 10,
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 2,
    type: '일반',
    sex: '여자',
    category: '손',
    pdName: '펌',
    num: 3,
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 3,
    type: '일반',
    sex: '여자',
    category: '속눈썹',
    pdName: '겨드랑이',
    num: 3,
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 4,
    type: '일반',
    sex: '남자',
    category: '왁싱',
    pdName: '젤네일',
    num: 10,
    price: 100000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 5,
    type: '일반',
    sex: '남자',
    category: '손',
    pdName: '페이스 + 상반신 맛사지',
    num: 10,
    price: 2000000,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
  {
    id: 6,
    type: '일반',
    sex: '남자',
    category: '피부관리',
    pdName: '페이스',
    price: 500000,
    num: 10,
    time: '60분',
    date: '2021-01-01',
    status: [{ id: 1, value: '판매중' }],
  },
];
