export const ReserveCaseData = [
  {
    id: 1,
    date: '2021-10-27 18:16',
    name: '홍길동',
    company: '랑스스킨앤바디',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '가상계좌',
    status: '결제대기',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '예약취소',
    admin: '관리',
  },
  {
    id: 2,
    date: '2021-10-27 18:16',
    name: '고길동',
    company: '맨들맨들1',
    paymentNum: '1905m0001',
    type: '이벤트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: -100000,
    sale: 0,
    payment: -100000,
    method: '신용카드',
    status: '결제취소',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '예약완료',
    admin: '관리',
  },
  {
    id: 3,
    date: '2021-10-27 18:16',
    name: '김길동',
    company: '맨들맨들2',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: -100000,
    sale: 0,
    payment: -100000,
    method: '금액권',
    status: '결제취소',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '예약요청',
    admin: '관리',
  },
  {
    id: 4,
    date: '2021-10-27 18:16',
    name: '이길동',
    company: '맨들맨들3',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 1000,
    payment: 99000,
    method: '정기권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 5,
    date: '2021-10-27 18:16',
    name: '최길동',
    company: '맨들맨들4',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 113000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 6,
    date: '2021-10-27 18:16',
    name: '홍길동',
    company: '맨들맨들5',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 7,
    date: '2021-10-27 18:16',
    name: '사길동',
    company: '맨들맨들6',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 8,
    date: '2021-10-27 18:16',
    name: '공길동',
    company: '맨들맨들7',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 9,
    date: '2021-10-27 18:16',
    name: '송길동',
    company: '맨들맨들8',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 10,
    date: '2021-10-27 18:16',
    name: '박길동',
    company: '맨들맨들9',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 11,
    date: '2021-10-27 18:16',
    name: '최길동',
    company: '맨들맨들1',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 12,
    date: '2021-10-27 18:16',
    name: '이길동',
    company: '맨들맨들2',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 13,
    date: '2021-10-27 18:16',
    name: '홍길동',
    company: '맨들맨들3',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 14,
    date: '2021-10-27 18:16',
    name: '파길동',
    company: '맨들맨들4',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 15,
    date: '2021-10-27 18:16',
    name: '오길동',
    company: '맨들맨들5',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 16,
    date: '2021-10-27 18:16',
    name: '유길동',
    company: '맨들맨들6',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 17,
    date: '2021-10-27 18:16',
    name: '리길동',
    company: '맨들맨들1',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 18,
    date: '2021-10-27 18:16',
    name: '여길동',
    company: '맨들맨들2',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 19,
    date: '2021-10-27 18:16',
    name: '표길동',
    company: '맨들맨들3',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 20,
    date: '2021-10-27 18:16',
    name: '민길동',
    company: '맨들맨들9',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 21,
    date: '2021-10-27 18:16',
    name: '김길동',
    company: '맨들맨들8',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 22,
    date: '2021-10-27 18:16',
    name: '고길동',
    company: '맨들맨들7',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 23,
    date: '2021-10-27 18:16',
    name: '민길동',
    company: '맨들맨들',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
  {
    id: 24,
    date: '2021-10-27 18:16',
    name: '홍길동',
    company: '맨들맨들',
    paymentNum: '1905m0001',
    type: '일반',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    price: 100000,
    sale: 0,
    payment: 100000,
    method: '금액권',
    status: '결제완료',
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    admin: '관리',
  },
];

export const ReserveShopData = [
  {
    id: 1,
    owner: '정우성',
    company: '맨들맨들1',
    area: '경기',
    grade: '일반',
    requestNum: 128,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 2,
    owner: '강경준',
    company: '맨들맨들2',
    area: '경기',
    grade: '일반',
    requestNum: 127,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 2,
    detail: '상세',
  },
  {
    id: 3,
    owner: '송강',
    company: '맨들맨들3',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 4,
    owner: '서지석',
    company: '맨들맨들5',
    area: '서울',
    grade: '파트너',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 5,
    owner: '권혁수',
    company: '맨들맨들5',
    area: '서울',
    grade: '파트너',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 6,
    owner: '공유',
    company: '맨들맨들6',
    area: '서울',
    grade: 'FC',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 7,
    owner: '박서준',
    company: '맨들맨들7',
    area: '서울',
    grade: 'FC',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 8,
    owner: '박광현',
    company: '맨들맨들8',
    area: '서울',
    grade: 'FC',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 9,
    owner: '송중기',
    company: '맨들맨들9',
    area: '서울',
    grade: '파트너',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 10,
    owner: '신성록',
    company: '맨들맨들10',
    area: '서울',
    grade: '파트너',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 11,
    owner: '정지훈',
    company: '맨들맨들11',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 12,
    owner: '정일우',
    company: '맨들맨들12',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 13,
    owner: '이서진',
    company: '맨들맨들13',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 14,
    owner: '이성열',
    company: '맨들맨들14',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 15,
    owner: '강태오',
    company: '맨들맨들15',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 16,
    owner: '옥택연',
    company: '맨들맨들16',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 17,
    owner: '유재석',
    company: '맨들맨들17',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 18,
    owner: '강동원',
    company: '맨들맨들18',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 19,
    owner: '원슈타인',
    company: '맨들맨들19',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 20,
    owner: '박해진',
    company: '맨들맨들20',
    area: '서울',
    grade: '일반',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 21,
    owner: '류진',
    company: '맨들맨들21',
    area: '서울',
    grade: '파트너',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 22,
    owner: '조승우',
    company: '맨들맨들22',
    area: '서울',
    grade: 'FC',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 23,
    owner: '홍길동',
    company: '맨들맨들23',
    area: '서울',
    grade: 'FC',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
  {
    id: 24,
    owner: '홍길동',
    company: '맨들맨들24',
    area: '서울',
    grade: '파트너',
    requestNum: 100,
    nail: 0,
    skincare: 0,
    eyelashes: 0,
    tanning: 0,
    waxing: 0,
    eyebrow: 0,
    footcare: 0,
    bodyshape: 0,
    massage: 0,
    cancelNum: 0,
    detail: '상세',
  },
];

export const ReserveShopDetailData = [
  {
    id: 1,
    date: '2021-10-27 18:16',
    name: '홍길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '가상계좌',
    status: '결제대기',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '예약완료',
    detail: '상세',
  },

  {
    id: 2,
    date: '2021-10-27 18:16',
    name: '고길동',
    paymentNum: '1905m0001',
    type: '이벤트',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '신용카드',
    status: '결제취소',
    payment: -100000,
    cancel: -500000,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '예약취소',
    detail: '상세',
  },
  {
    id: 3,
    date: '2021-10-27 18:16',
    name: '김길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제취소',
    payment: -100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '예약완료',
    detail: '상세',
  },
  {
    id: 4,
    date: '2021-10-27 18:16',
    name: '이길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '정기권',
    status: '결제완료',
    payment: 99000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 5,
    date: '2021-10-27 18:16',
    name: '최길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 6,
    date: '2021-10-27 18:16',
    name: '홍길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 7,
    date: '2021-10-27 18:16',
    name: '사길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 8,
    date: '2021-10-27 18:16',
    name: '공길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 9,
    date: '2021-10-27 18:16',
    name: '송길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 10,
    date: '2021-10-27 18:16',
    name: '박길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 11,
    date: '2021-10-27 18:16',
    name: '최길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 12,
    date: '2021-10-27 18:16',
    name: '이길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 13,
    date: '2021-10-27 18:16',
    name: '홍길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '왁싱',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 14,
    date: '2021-10-27 18:16',
    name: '파길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 15,
    date: '2021-10-27 18:16',
    name: '오길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 16,
    date: '2021-10-27 18:16',
    name: '유길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '왁싱',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 17,
    date: '2021-10-27 18:16',
    name: '리길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 18,
    date: '2021-10-27 18:16',
    name: '여길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 19,
    date: '2021-10-27 18:16',
    name: '표길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '왁싱',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 20,
    date: '2021-10-27 18:16',
    name: '민길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
  {
    id: 21,
    date: '2021-10-27 18:16',
    name: '김길동',
    paymentNum: '1905m0001',
    type: '일반',
    category: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    method: '금액권',
    status: '결제완료',
    payment: 100000,
    cancel: 0,
    reservationDate: 'YYYY-MM-DD HH:MM',
    reservationStatus: '이용완료',
    detail: '상세',
  },
];
