export const ReviewData = [
  {
    id: 1,
    date: 'YYYY_MM_DD',
    name: '정우성',
    company: '맨들맨들1',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 2,
    date: 'YYYY_MM_DD',
    name: '강경준',
    company: '맨들맨들2',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 3,
    date: 'YYYY_MM_DD',
    name: '송강',
    company: '맨들맨들3',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 4,
    date: 'YYYY_MM_DD',
    name: '서지석',
    company: '맨들맨들4',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 5,
    date: 'YYYY_MM_DD',
    name: '권혁수',
    company: '맨들맨들5',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '미답변',
    admin: '상세',
  },
  {
    id: 6,
    date: 'YYYY_MM_DD',
    name: '공유',
    company: '맨들맨들6',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 7,
    date: 'YYYY_MM_DD',
    name: '박서준',
    company: '맨들맨들7',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 1,
    reviewCount: 1,
    scope: 1,
    grade: 1,
    best: '추천안함',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 8,
    date: 'YYYY_MM_DD',
    name: '박광현',
    company: '맨들맨들8',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천안함',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 9,
    date: 'YYYY_MM_DD',
    name: '송중기',
    company: '맨들맨들9',
    cate: '왁싱',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 10,
    date: 'YYYY_MM_DD',
    name: '신성록',
    company: '맨들맨들10',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 11,
    date: 'YYYY_MM_DD',
    name: '정지훈',
    company: '맨들맨들11',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 12,
    date: 'YYYY_MM_DD',
    name: '정일우',
    company: '맨들맨들12',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 13,
    date: 'YYYY_MM_DD',
    name: '이서진',
    company: '맨들맨들13',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 14,
    date: 'YYYY_MM_DD',
    name: '이성열',
    company: '맨들맨들14',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 15,
    date: 'YYYY_MM_DD',
    name: '강태오',
    company: '맨들맨들15',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 16,
    date: 'YYYY_MM_DD',
    name: '옥택연',
    company: '맨들맨들16',
    cate: '왁싱',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 17,
    date: 'YYYY_MM_DD',
    name: '유재석',
    company: '맨들맨들17',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 18,
    date: 'YYYY_MM_DD',
    name: '강동원',
    company: '맨들맨들18',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 19,
    date: 'YYYY_MM_DD',
    name: '원슈타인',
    company: '맨들맨들19',
    cate: '왁싱',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 20,
    date: 'YYYY_MM_DD',
    name: '박해진',
    company: '맨들맨들20',
    cate: '왁싱',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 21,
    date: 'YYYY_MM_DD',
    name: '류진',
    company: '맨들맨들21',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 22,
    date: 'YYYY_MM_DD',
    name: '조승우',
    company: '맨들맨들22',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 23,
    date: 'YYYY_MM_DD',
    name: '홍길동',
    company: '맨들맨들23',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
  {
    id: 24,
    date: 'YYYY_MM_DD',
    name: '홍길동',
    company: '맨들맨들24',
    cate: '네일아트',
    prodcut: '[왁싱/여성/바디왁싱] 다리하프',
    reservationCases: 5,
    reviewCount: 5,
    scope: 5,
    grade: 5,
    best: '추천',
    answer: '답변완료',
    admin: '상세',
  },
];

export default ReviewData;
