import ServiceImage1 from '../assets/sevice-img-01.jpg';
import ServiceImage2 from '../assets/sevice-img-02.jpg';
import ServiceImage3 from '../assets/sevice-img-03.jpg';
import ServiceImage4 from '../assets/sevice-img-04.jpg';
import ServiceImage5 from '../assets/sevice-img-05.jpg';
import ServiceImage6 from '../assets/sevice-img-06.jpg';

export const ServiceMainBannerData = [
  {
    id: 1,
    title: '일반',
    imgSrc: ServiceImage1,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 2,
    title: '일반',
    imgSrc: ServiceImage2,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 3,
    title: '일반',
    imgSrc: ServiceImage3,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 4,
    title: '일반',
    imgSrc: ServiceImage4,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 5,
    title: '일반',
    imgSrc: ServiceImage5,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 6,
    title: '일반',
    imgSrc: ServiceImage6,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
];

export const ServiceSubBannerData = [
  {
    id: 1,
    title: '일반',
    imgSrc: ServiceImage1,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 2,
    title: '일반',
    imgSrc: ServiceImage2,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 3,
    title: '일반',
    imgSrc: ServiceImage3,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 4,
    title: '일반',
    imgSrc: ServiceImage4,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 5,
    title: '일반',
    imgSrc: ServiceImage5,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 6,
    title: '일반',
    imgSrc: ServiceImage6,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '활성' },
      { id: 2, value: '비활성' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
];

export const ServiceEventData = [
  {
    id: 1,
    title: '신년 이벤트',
    imgSrc: ServiceImage1,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '진행' },
      { id: 2, value: '종료' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 2,
    title: '새해 맞이 인증 이벤트',
    imgSrc: ServiceImage2,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '진행' },
      { id: 2, value: '종료' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 3,
    title: '친구도 만원 나도 만원 추천하고 네일받기',
    imgSrc: ServiceImage3,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '진행' },
      { id: 2, value: '종료' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 4,
    title: '매일매일 출석체크',
    imgSrc: ServiceImage4,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '진행' },
      { id: 2, value: '종료' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 5,
    title: '일반',
    imgSrc: ServiceImage5,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '진행' },
      { id: 2, value: '종료' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
  {
    id: 6,
    title: '일반',
    imgSrc: ServiceImage6,
    term: 'YYYY-MM-DD HH:MM - YYYY-MM-DD HH:MM',
    status: [
      { id: 1, value: '진행' },
      { id: 2, value: '종료' },
    ],
    date: '2021-01-01',
    admin: '관리',
  },
];

export const ServiceCouponData = [
  {
    id: 1,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '손',
    IssuedNum: 100000,
    usedNum: 100000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 2,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '손',
    IssuedNum: 100000,
    usedNum: 100000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 3,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '손',
    IssuedNum: 100000,
    usedNum: 100000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 4,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '손',
    IssuedNum: 100000,
    usedNum: 100000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 5,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '손',
    IssuedNum: 100000,
    usedNum: 100000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 6,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '손',
    IssuedNum: 100000,
    usedNum: 100000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 7,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '손',
    IssuedNum: 100000,
    usedNum: 100000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 8,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '손',
    IssuedNum: 20000,
    usedNum: 20000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 9,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '발',
    IssuedNum: 30000,
    usedNum: 30000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 10,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '발',
    IssuedNum: 100000,
    usedNum: 100000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
  {
    id: 11,
    name: '일반',
    pay: 1000,
    shape: '대상형',
    detail: '발',
    IssuedNum: 100000,
    usedNum: 100000,
    date: '2021-01-01',
    status: [
      {
        id: 1,
        value: '판매중',
      },
      {
        id: 2,
        value: '판매종료',
      },
    ],
  },
];

export const ServiceDeclarationData = [
  {
    id: 1,
    name: '정우성',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 2,
    name: '강경준',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 3,
    name: '송강',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 4,
    name: '서지석',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 5,
    name: '권혁수',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 6,
    name: '공유',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 7,
    name: '박서준',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 8,
    name: '박광현',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 9,
    name: '송**',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 10,
    name: '신성록',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 11,
    name: '정지훈',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 12,
    name: '정일우',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 13,
    name: '이서진',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 14,
    name: '이성열',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 15,
    name: '강태오',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 16,
    name: '옥택연',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 17,
    name: '유재석',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 18,
    name: '강동원',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 19,
    name: '원슈타인',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 20,
    name: '박해진',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 21,
    name: '류진',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 22,
    name: '조승우',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 23,
    name: '홍길동',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
  {
    id: 24,
    name: '홍길동',
    phone: '010-1111-2222',
    pay: 278000,
    point: 0,
    date: 'YYYY-MM-DD',
    admin: '관리',
  },
];
