const RegistrationRequestData = [
  {
    id: 1,
    company: '맨들맨들1',
    owner: '정우성',
    area: '경기',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 2,
    company: '맨들맨들2',
    owner: '강경준',
    area: '경기',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 3,
    company: '맨들맨들3',
    owner: '송강',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 4,
    company: '맨들맨들5',
    owner: '서지석',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 5,
    company: '맨들맨들5',
    owner: '권혁수',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 6,
    company: '맨들맨들6',
    owner: '공유',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 7,
    company: '맨들맨들7',
    owner: '박서준',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 8,
    company: '맨들맨들8',
    owner: '박광현',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 9,
    company: '맨들맨들9',
    owner: '송중기',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 10,
    company: '맨들맨들10',
    owner: '신성록',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 11,
    company: '맨들맨들11',
    owner: '정지훈',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 12,
    company: '맨들맨들12',
    owner: '정일우',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 13,
    company: '맨들맨들13',
    owner: '이서진',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 14,
    company: '맨들맨들14',
    owner: '이성열',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 15,
    company: '맨들맨들15',
    owner: '강태오',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 16,
    company: '맨들맨들16',
    owner: '옥택연',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 17,
    company: '맨들맨들17',
    owner: '유재석',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 18,
    company: '맨들맨들18',
    owner: '강동원',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 19,
    company: '맨들맨들19',
    owner: '원슈타인',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 20,
    company: '맨들맨들20',
    owner: '박해진',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 21,
    company: '맨들맨들21',
    owner: '류진',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 22,
    company: '맨들맨들22',
    owner: '조승우',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 23,
    company: '맨들맨들',
    owner: '홍길동',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
  {
    id: 24,
    company: '맨들맨들',
    owner: '홍길동',
    area: '서울',
    phone: '010-1111-2222',
    category: '네일아트 , 피부관리',
    signUpDate: 'YYYY-MM-DD',
    registrationRequestDate: 'YYYY-MM-DD',
    manager: '박동희',
    admin: '관리',
  },
];

export default RegistrationRequestData;
